version: "3.3"

services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    cap_add:
      - net_admin
    environment:
      - DNS=${VPN_DNS}
      - TZ=${TIMEZONE}
    networks:
      default:
        ipv4_address: 172.20.50.2
    read_only: false
    tmpfs:
      - /run
      - /tmp
    restart: unless-stopped
    security_opt:
      - label:disable
    stdin_open: true
    tty: true
    volumes:
      - /dev/net:/dev/net:z
      - ${CONTAINERS}/openvpn:/vpn
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      #
      # Exposed containers
      # See more @ https://community.containo.us/t/docker-compose-with-network-mode-service-service-name/3395
      #
      - traefik.http.routers.deluge.entrypoints=websecured
      - traefik.http.routers.deluge.tls.certresolver=myresolver
      - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN}`)
    ports:
      - 8112:8112 # Deluge

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    network_mode: service:vpn
    depends_on:
      - vpn
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.deluge.rule=Host(`deluge.${DOMAIN}`)
      - traefik.http.routers.deluge.entrypoints=websecured
      - traefik.http.routers.deluge.tls.certresolver=myresolver
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONTAINERS}/deluge/config:/config
      - ${DOWNLOADS}/torrents:/downloads
      - ./themes/deluge/${DELUGE_THEME}.css:/usr/lib/python3/dist-packages/deluge/ui/web/themes/css/xtheme-gray.css
    restart: unless-stopped
