version: "3.3"

services:
  plex:
    volumes:
      - /data/extra/media/tv:/wd-4tb-tv
      - /data/extra/media/movies:/wd-4tb-movies
  
  sonarr:
    volumes:
      - /data/extra/media/tv:/wd-4tb-tv

  radarr:
    volumes:
      - /data/extra/media/movies:/wd-4tb-movies

  bazarr:
    volumes:
      - /data/extra/media/tv:/wd-4tb-tv
      - /data/extra/media/movies:/wd-4tb-movies

