version: "3.3"

services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    networks:
      default:
        ipv4_address: 172.20.2.6
    ports:
      - 8083:8083
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.calibreweb.rule=Host(`calibre-web.${DOMAIN}`)
      - traefik.http.routers.calibreweb.entrypoints=websecured
      - traefik.http.routers.calibreweb.tls.certresolver=myresolver
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${CONTAINERS}/calibre-web/config:/config
      - ${CONTAINERS}/calibre-web/books:/books
    restart: unless-stopped

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    networks:
      default:
        ipv4_address: 172.20.2.7
    ports:
      - 13378:80
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobookshelf.${DOMAIN}`)
      - traefik.http.routers.audiobookshelf.entrypoints=websecured
      - traefik.http.routers.audiobookshelf.tls.certresolver=myresolver
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${CONTAINERS}/audiobookshelf/audiobooks:/audiobooks
      - ${CONTAINERS}/audiobookshelf/podcasts:/podcasts
      - ${CONTAINERS}/audiobookshelf/config:/config
      - ${CONTAINERS}/audiobookshelf/metadata:/metadata
    restart: unless-stopped
