name: Multimedia Stack Deployment

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Run tests for any tags.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Main Stack Deployment + VPN Protected Torrenting
        run: docker-compose -f docker-compose.yml -f docker-compose.torrents-on-vpn.yml up -d
